### ISSUE TITLE
Correct Configuration:

### ISSUE THREAD

**Issue by aintHuman** [dylantack/redis-token-bucket#1]
I am trying to use this for distributed rate-limiting queries to an external API. Like, for example, I have a fleet of AWS EC2 Machines behind a load balancer, and a workload is distributed across these machines, and collectively, they can only make X queries per minute to the external API.

So If my rate limit is a maximum 30 queries per minute, would the following configuration be correct ? 

```
 const res = (
      await redisTokenBucketConsumer(
          'myscope', 
          { 
              refill_interval_ms : 60 * 1000, // ms per minute 
              max_bucket_size : 30
          } 
      )
  )
```

If so, the expected rate is not happening (its being throttled much slower), I am wondering in your code, whether the below line is correct:

`const expire = Math.ceil(config.refill_interval_ms * config.max_bucket_size / 1000);`

Why would the expire figure be the `refill_interval_ms` **MULTIPLIED** by the bucket size ?

**Comment by dylantack** [comment]
`refill_interval_ms` means how often **1** additional token is added (not the total time to fill the bucket).

So to express "30 tokens per minute", the interval is 60/30 = 2 seconds.
